#ifndef GUI_DIMENSIONS_H
#define GUI_DIMENSIONS_H

#define SCREEN_WIDTH  320
#define SCREEN_HEIGHT 240

#define STATUS_BAR_HEIGHT 20
#define TITLE_BAR_HEIGHT  40

#define DEFAULT_PADDING 4

#endif // GUI_DIMENSIONS_H
