#ifndef GUI_DIMENSIONS_H
#define GUI_DIMENSIONS_H

#define GUI_SCREEN_WIDTH  320
#define GUI_SCREEN_HEIGHT 240

#define GUI_STATUS_BAR_HEIGHT 20
#define GUI_TITLE_BAR_HEIGHT 50

#define GUI_DEFAULT_PADDING 4

#endif // GUI_DIMENSIONS_H
